/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    'guild-settings': GuildSetting;
    progression: Progression;
    'officers-section': OfficersSection;
    'recruitment-section': RecruitmentSection;
    roster: Roster;
    'guild-details': GuildDetail;
  };
  globalsSelect: {
    'guild-settings': GuildSettingsSelect<false> | GuildSettingsSelect<true>;
    progression: ProgressionSelect<false> | ProgressionSelect<true>;
    'officers-section': OfficersSectionSelect<false> | OfficersSectionSelect<true>;
    'recruitment-section': RecruitmentSectionSelect<false> | RecruitmentSectionSelect<true>;
    roster: RosterSelect<false> | RosterSelect<true>;
    'guild-details': GuildDetailSelect<false> | GuildDetailSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "guild-settings".
 */
export interface GuildSetting {
  id: number;
  /**
   * Small label above the About section heading.
   */
  eyebrow?: string | null;
  /**
   * Main heading of the About section.
   */
  heading?: string | null;
  name: string;
  tagline?: string | null;
  server?: string | null;
  region?: string | null;
  faction?: string | null;
  /**
   * Guild description shown on the About section. Supports bold, italic, lists, links.
   */
  description?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Links shown in the site footer.
   */
  footerLinks?:
    | {
        label: string;
        href: string;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "progression".
 */
export interface Progression {
  id: number;
  tier: string;
  difficulty?: ('Normal' | 'Heroic' | 'Mythic') | null;
  /**
   * e.g. "6/9 H" — auto-filled by Raider.IO sync
   */
  summary?: string | null;
  kills?: number | null;
  totalBosses?: number | null;
  /**
   * Raider.IO profile URL
   */
  profileUrl?: string | null;
  rankings?: {
    /**
     * Auto-filled by sync — total guild member count
     */
    members?: number | null;
    world?: number | null;
    region?: number | null;
    realm?: number | null;
  };
  bosses?:
    | {
        name: string;
        killed?: boolean | null;
        /**
         * Number of pulls (for in-progress bosses)
         */
        pulls?: number | null;
        /**
         * Best pull % (for in-progress bosses)
         */
        bestPull?: number | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Last time data was synced from Raider.IO
   */
  lastSyncedAt?: string | null;
  guildMembers?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Top 10 M+ runners — auto-filled by Raider.IO sync or add manually
   */
  mythicPlusRunners?:
    | {
        name: string;
        class: string;
        spec: string;
        score: number;
        id?: string | null;
      }[]
    | null;
  /**
   * Last time M+ data was synced from Raider.IO
   */
  mythicPlusSyncedAt?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "officers-section".
 */
export interface OfficersSection {
  id: number;
  /**
   * Small label above the section heading.
   */
  eyebrow?: string | null;
  /**
   * Main section heading.
   */
  heading?: string | null;
  officers?:
    | {
        name: string;
        class?:
          | (
              | 'Death Knight'
              | 'Demon Hunter'
              | 'Druid'
              | 'Evoker'
              | 'Hunter'
              | 'Mage'
              | 'Monk'
              | 'Paladin'
              | 'Priest'
              | 'Rogue'
              | 'Shaman'
              | 'Warlock'
              | 'Warrior'
            )
          | null;
        spec?: string | null;
        role?: ('Tank' | 'Healer' | 'DPS') | null;
        ilvl?: number | null;
        rank?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "recruitment-section".
 */
export interface RecruitmentSection {
  id: number;
  /**
   * Small label above the section heading.
   */
  eyebrow?: string | null;
  /**
   * Main section heading.
   */
  heading?: string | null;
  /**
   * Paragraph shown below the heading.
   */
  description?: string | null;
  /**
   * Small text shown below the Apply button.
   */
  footerNote?: string | null;
  /**
   * Label on the Apply button.
   */
  ctaLabel?: string | null;
  /**
   * Discord invite link for the Apply button.
   */
  discordUrl?: string | null;
  roles?:
    | {
        role: 'Tank' | 'Healer' | 'DPS';
        specs?:
          | {
              spec: string;
              id?: string | null;
            }[]
          | null;
        priority?: ('High' | 'Medium' | 'Low') | null;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "roster".
 */
export interface Roster {
  id: number;
  members?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Last time roster was synced from Raider.IO
   */
  lastSyncedAt?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "guild-details".
 */
export interface GuildDetail {
  id: number;
  details?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Last time guild details were synced from Raider.IO
   */
  lastSyncedAt?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "guild-settings_select".
 */
export interface GuildSettingsSelect<T extends boolean = true> {
  eyebrow?: T;
  heading?: T;
  name?: T;
  tagline?: T;
  server?: T;
  region?: T;
  faction?: T;
  description?: T;
  footerLinks?:
    | T
    | {
        label?: T;
        href?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "progression_select".
 */
export interface ProgressionSelect<T extends boolean = true> {
  tier?: T;
  difficulty?: T;
  summary?: T;
  kills?: T;
  totalBosses?: T;
  profileUrl?: T;
  rankings?:
    | T
    | {
        members?: T;
        world?: T;
        region?: T;
        realm?: T;
      };
  bosses?:
    | T
    | {
        name?: T;
        killed?: T;
        pulls?: T;
        bestPull?: T;
        id?: T;
      };
  lastSyncedAt?: T;
  guildMembers?: T;
  mythicPlusRunners?:
    | T
    | {
        name?: T;
        class?: T;
        spec?: T;
        score?: T;
        id?: T;
      };
  mythicPlusSyncedAt?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "officers-section_select".
 */
export interface OfficersSectionSelect<T extends boolean = true> {
  eyebrow?: T;
  heading?: T;
  officers?:
    | T
    | {
        name?: T;
        class?: T;
        spec?: T;
        role?: T;
        ilvl?: T;
        rank?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "recruitment-section_select".
 */
export interface RecruitmentSectionSelect<T extends boolean = true> {
  eyebrow?: T;
  heading?: T;
  description?: T;
  footerNote?: T;
  ctaLabel?: T;
  discordUrl?: T;
  roles?:
    | T
    | {
        role?: T;
        specs?:
          | T
          | {
              spec?: T;
              id?: T;
            };
        priority?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "roster_select".
 */
export interface RosterSelect<T extends boolean = true> {
  members?: T;
  lastSyncedAt?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "guild-details_select".
 */
export interface GuildDetailSelect<T extends boolean = true> {
  details?: T;
  lastSyncedAt?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}